
package notenservice.wsexport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotenService", targetNamespace = "http://ws.notenservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotenService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns notenservice.wsexport.Notenliste
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.notenservice/NotenService/getMarksRequest", output = "http://ws.notenservice/NotenService/getMarksResponse")
    public Notenliste getMarks(
        @WebParam(name = "arg0", partName = "arg0")
        Punkteliste arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Notenskala arg1);

}
