<definitions
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
xmlns:wsp="http://www.w3.org/ns/ws-policy"
xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.test/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ws.test/"
name="NotenServiceService">
<types>
<xs:schema xmlns:tns="http://ws.test/"
xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"
targetNamespace="http://ws.test/">
<xs:complexType name="studentenliste">
<xs:sequence>
<xs:element name="studentenliste" type="tns:student" nillable="true"
minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="student">
<xs:sequence/>
</xs:complexType>
</xs:schema>
</types>
<message name="getMarks">
<part name="arg0" type="tns:studentenliste"/>
</message>
<message name="getMarksResponse">
<part name="return" type="tns:studentenliste"/>
</message>
<portType name="NotenService">
<operation name="getMarks">
<input wsam:Action="http://ws.test/NotenService/getMarksRequest"
message="tns:getMarks"/>
<output wsam:Action="http://ws.test/NotenService/getMarksResponse"
message="tns:getMarksResponse"/>
</operation>
</portType>
<binding name="NotenServicePortBinding" type="tns:NotenService">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
<operation name="getMarks">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal" namespace="http://ws.test/"/>
</input>
<output>
<soap:body use="literal" namespace="http://ws.test/"/>
</output>
</operation>
</binding>
<service name="NotenServiceService">
<port name="NotenServicePort" binding="tns:NotenServicePortBinding">
<soap:address location="http://localhost:9999/hello"/>
</port>
</service>
</definitions>
