
package notenstatus.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Notenstatus", targetNamespace = "http://ws.notenstatus/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Notenstatus {


    /**
     * 
     * @param arg0
     * @return
     *     returns notenstatus.ws.Notenstatus_Type
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.notenstatus/Notenstatus/getNotenstatusRequest", output = "http://ws.notenstatus/Notenstatus/getNotenstatusResponse")
    public Notenstatus_Type getNotenstatus(
        @WebParam(name = "arg0", partName = "arg0")
        Notenliste arg0);

}
