
package notenstatus.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotenstatusService", targetNamespace = "http://ws.notenstatus/", wsdlLocation = "file:/home/nvetter/Projekte/Uni/SOA/Zulassung/Aufgabe2/zulassung.wsdl")
public class NotenstatusService
    extends Service
{

    private final static URL NOTENSTATUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTENSTATUSSERVICE_EXCEPTION;
    private final static QName NOTENSTATUSSERVICE_QNAME = new QName("http://ws.notenstatus/", "NotenstatusService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/nvetter/Projekte/Uni/SOA/Zulassung/Aufgabe2/zulassung.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTENSTATUSSERVICE_WSDL_LOCATION = url;
        NOTENSTATUSSERVICE_EXCEPTION = e;
    }

    public NotenstatusService() {
        super(__getWsdlLocation(), NOTENSTATUSSERVICE_QNAME);
    }

    public NotenstatusService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTENSTATUSSERVICE_QNAME, features);
    }

    public NotenstatusService(URL wsdlLocation) {
        super(wsdlLocation, NOTENSTATUSSERVICE_QNAME);
    }

    public NotenstatusService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTENSTATUSSERVICE_QNAME, features);
    }

    public NotenstatusService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotenstatusService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Notenstatus
     */
    @WebEndpoint(name = "NotenstatusPort")
    public Notenstatus getNotenstatusPort() {
        return super.getPort(new QName("http://ws.notenstatus/", "NotenstatusPort"), Notenstatus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Notenstatus
     */
    @WebEndpoint(name = "NotenstatusPort")
    public Notenstatus getNotenstatusPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.notenstatus/", "NotenstatusPort"), Notenstatus.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTENSTATUSSERVICE_EXCEPTION!= null) {
            throw NOTENSTATUSSERVICE_EXCEPTION;
        }
        return NOTENSTATUSSERVICE_WSDL_LOCATION;
    }

}
