# Target specific macros
TARGET = nxtrobotmain_OSEK
TARGET_SOURCES = \
	nxtrobotmain.c \
	light.c \
	motor.c \
	motorik.c \
	bluetooth.c
TOPPERS_OSEK_OIL_SOURCE = ./nxtrobotmain.oil
ROOT=$(nxtOSEK)

# Don't modify below part
O_PATH ?= build
include $(nxtOSEK)/ecrobot/ecrobot.mak
