# Target specific macros
TARGET = nxtRobotMain_OSEK
TARGET_SOURCES = \
	nxtRobotMain.c \
	motorik.c
TOPPERS_OSEK_OIL_SOURCE = ./nxtRobotMain.oil
ROOT=$(nxtOSEK)

# Don't modify below part
O_PATH ?= build
include $(nxtOSEK)/ecrobot/ecrobot.mak
